# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@markhuang19994'
      - run: npm ci
      - run: node build-output.js

      - name: Publish new design token version
        run: |
          cd design-token || exit 1
          mv ../build/css/* .
          
          # check any change
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./*
          git commit -m "check any change" || exit 0
          
          # update package version via commit message
          COMMIT_MSG=$(git log -2 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            npm version major
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            npm version minor
          else
            npm version patch
          fi
          
          # publish to npm repository
          npm publish
          
          # push new package version
          git reset --soft HEAD^1
          git add package.json
          git commit -m "Update lib version [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
